// ============================================================
// Mock Data for Urja Dental Clinic Admin Dashboard
// ============================================================

import type {
  Appointment,
  Patient,
  Doctor,
  Service,
  BlogPost,
  GalleryImage,
  Testimonial,
  Enquiry,
  User,
  ActivityLog,
  Backup,
  Redirect,
  SEOScore,
} from "./types";

export const mockAppointments: Appointment[] = [
  {
    _id: "apt_1",
    patientName: "Rahul Sharma",
    patientPhone: "+91 98765 43210",
    patientEmail: "rahul.sharma@email.com",
    service: "Teeth Whitening",
    serviceId: "svc_1",
    doctor: "Dr. Amit Mehta",
    doctorId: "doc_1",
    date: "2026-02-06",
    time: "10:00 AM",
    status: "confirmed",
    notes: "First visit patient",
    createdAt: "2026-02-05T10:00:00Z",
    updatedAt: "2026-02-05T10:00:00Z",
  },
  {
    _id: "apt_2",
    patientName: "Priya Patel",
    patientPhone: "+91 87654 32109",
    patientEmail: "priya.patel@email.com",
    service: "Dental Implant Consultation",
    serviceId: "svc_2",
    doctor: "Dr. Sneha Sharma",
    doctorId: "doc_2",
    date: "2026-02-06",
    time: "11:30 AM",
    status: "pending",
    createdAt: "2026-02-05T11:00:00Z",
    updatedAt: "2026-02-05T11:00:00Z",
  },
  {
    _id: "apt_3",
    patientName: "Amit Kumar",
    patientPhone: "+91 76543 21098",
    patientEmail: "amit.kumar@email.com",
    service: "Root Canal Treatment",
    serviceId: "svc_3",
    doctor: "Dr. Amit Mehta",
    doctorId: "doc_1",
    date: "2026-02-06",
    time: "2:00 PM",
    status: "confirmed",
    notes: "Follow-up session 3",
    createdAt: "2026-02-04T14:00:00Z",
    updatedAt: "2026-02-05T09:00:00Z",
  },
  {
    _id: "apt_4",
    patientName: "Sneha Reddy",
    patientPhone: "+91 65432 10987",
    patientEmail: "sneha.reddy@email.com",
    service: "Braces Consultation",
    serviceId: "svc_4",
    doctor: "Dr. Rajesh Gupta",
    doctorId: "doc_3",
    date: "2026-02-06",
    time: "3:30 PM",
    status: "pending",
    createdAt: "2026-02-05T15:00:00Z",
    updatedAt: "2026-02-05T15:00:00Z",
  },
  {
    _id: "apt_5",
    patientName: "Vikram Joshi",
    patientPhone: "+91 54321 09876",
    patientEmail: "vikram.joshi@email.com",
    service: "Dental Cleaning",
    serviceId: "svc_5",
    doctor: "Dr. Sneha Sharma",
    doctorId: "doc_2",
    date: "2026-02-06",
    time: "5:00 PM",
    status: "confirmed",
    createdAt: "2026-02-05T16:00:00Z",
    updatedAt: "2026-02-05T16:00:00Z",
  },
  {
    _id: "apt_6",
    patientName: "Neha Singh",
    patientPhone: "+91 43210 98765",
    patientEmail: "neha.singh@email.com",
    service: "Teeth Whitening",
    serviceId: "svc_1",
    doctor: "Dr. Amit Mehta",
    doctorId: "doc_1",
    date: "2026-02-07",
    time: "10:00 AM",
    status: "cancelled",
    notes: "Patient requested cancellation",
    createdAt: "2026-02-04T10:00:00Z",
    updatedAt: "2026-02-05T08:00:00Z",
  },
  {
    _id: "apt_7",
    patientName: "Karan Malhotra",
    patientPhone: "+91 32109 87654",
    patientEmail: "karan.m@email.com",
    service: "Dental Implant",
    serviceId: "svc_2",
    doctor: "Dr. Sneha Sharma",
    doctorId: "doc_2",
    date: "2026-02-07",
    time: "11:00 AM",
    status: "confirmed",
    createdAt: "2026-02-05T12:00:00Z",
    updatedAt: "2026-02-05T12:00:00Z",
  },
  {
    _id: "apt_8",
    patientName: "Ananya Desai",
    patientPhone: "+91 21098 76543",
    patientEmail: "ananya.d@email.com",
    service: "Smile Makeover",
    serviceId: "svc_6",
    doctor: "Dr. Amit Mehta",
    doctorId: "doc_1",
    date: "2026-02-08",
    time: "2:00 PM",
    status: "pending",
    createdAt: "2026-02-05T14:00:00Z",
    updatedAt: "2026-02-05T14:00:00Z",
  },
];

export const mockPatients: Patient[] = [
  {
    _id: "pat_1",
    name: "Rahul Sharma",
    email: "rahul.sharma@email.com",
    phone: "+91 98765 43210",
    dateOfBirth: "1990-05-15",
    gender: "male",
    address: "123 MG Road, Mumbai, Maharashtra 400001",
    medicalHistory: "No known allergies",
    createdAt: "2025-06-15T10:00:00Z",
    updatedAt: "2026-02-05T10:00:00Z",
  },
  {
    _id: "pat_2",
    name: "Priya Patel",
    email: "priya.patel@email.com",
    phone: "+91 87654 32109",
    dateOfBirth: "1988-08-22",
    gender: "female",
    address: "456 Park Street, Pune, Maharashtra 411001",
    medicalHistory: "Mild penicillin allergy",
    allergies: "Penicillin",
    createdAt: "2025-07-20T11:00:00Z",
    updatedAt: "2026-02-05T11:00:00Z",
  },
  {
    _id: "pat_3",
    name: "Amit Kumar",
    email: "amit.kumar@email.com",
    phone: "+91 76543 21098",
    dateOfBirth: "1985-03-10",
    gender: "male",
    address: "789 Brigade Road, Bangalore, Karnataka 560001",
    medicalHistory: "Diabetes Type 2, Regular medication",
    createdAt: "2025-05-10T14:00:00Z",
    updatedAt: "2026-02-04T14:00:00Z",
  },
  {
    _id: "pat_4",
    name: "Sneha Reddy",
    email: "sneha.reddy@email.com",
    phone: "+91 65432 10987",
    dateOfBirth: "1995-11-28",
    gender: "female",
    address: "321 Jubilee Hills, Hyderabad, Telangana 500033",
    createdAt: "2025-09-05T15:00:00Z",
    updatedAt: "2026-02-05T15:00:00Z",
  },
  {
    _id: "pat_5",
    name: "Vikram Joshi",
    email: "vikram.joshi@email.com",
    phone: "+91 54321 09876",
    dateOfBirth: "1992-07-04",
    gender: "male",
    address: "654 Sector 17, Chandigarh 160017",
    createdAt: "2025-08-12T16:00:00Z",
    updatedAt: "2026-02-05T16:00:00Z",
  },
];

export const mockDoctors: Doctor[] = [
  {
    _id: "doc_1",
    name: "Dr. Amit Mehta",
    slug: "dr-amit-mehta",
    photo: "/doctors/dr-amit-mehta.jpg",
    qualification: "BDS, MDS (Prosthodontics)",
    experience: 15,
    specializations: ["Dental Implants", "Smile Makeover", "Teeth Whitening"],
    bio: "Dr. Amit Mehta is a leading prosthodontist with over 15 years of experience in cosmetic and restorative dentistry. He has performed over 5000 successful dental implant procedures.",
    schedule: [
      { day: "Monday", startTime: "09:00", endTime: "17:00", isAvailable: true },
      { day: "Tuesday", startTime: "09:00", endTime: "17:00", isAvailable: true },
      { day: "Wednesday", startTime: "09:00", endTime: "17:00", isAvailable: true },
      { day: "Thursday", startTime: "09:00", endTime: "17:00", isAvailable: true },
      { day: "Friday", startTime: "09:00", endTime: "17:00", isAvailable: true },
      { day: "Saturday", startTime: "09:00", endTime: "13:00", isAvailable: true },
      { day: "Sunday", startTime: "", endTime: "", isAvailable: false },
    ],
    consultationFees: 1000,
    isActive: true,
    order: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    _id: "doc_2",
    name: "Dr. Sneha Sharma",
    slug: "dr-sneha-sharma",
    photo: "/doctors/dr-sneha-sharma.jpg",
    qualification: "BDS, MDS (Oral Surgery)",
    experience: 12,
    specializations: ["Oral Surgery", "Dental Implants", "Wisdom Tooth Extraction"],
    bio: "Dr. Sneha Sharma specializes in oral and maxillofacial surgery with expertise in complex dental implant procedures and wisdom tooth extractions.",
    schedule: [
      { day: "Monday", startTime: "10:00", endTime: "18:00", isAvailable: true },
      { day: "Tuesday", startTime: "10:00", endTime: "18:00", isAvailable: true },
      { day: "Wednesday", startTime: "10:00", endTime: "18:00", isAvailable: true },
      { day: "Thursday", startTime: "10:00", endTime: "18:00", isAvailable: true },
      { day: "Friday", startTime: "10:00", endTime: "18:00", isAvailable: true },
      { day: "Saturday", startTime: "10:00", endTime: "14:00", isAvailable: true },
      { day: "Sunday", startTime: "", endTime: "", isAvailable: false },
    ],
    consultationFees: 800,
    isActive: true,
    order: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    _id: "doc_3",
    name: "Dr. Rajesh Gupta",
    slug: "dr-rajesh-gupta",
    photo: "/doctors/dr-rajesh-gupta.jpg",
    qualification: "BDS, MDS (Orthodontics)",
    experience: 10,
    specializations: ["Braces", "Invisalign", "Pediatric Orthodontics"],
    bio: "Dr. Rajesh Gupta is an experienced orthodontist specializing in both traditional braces and clear aligner therapy for patients of all ages.",
    schedule: [
      { day: "Monday", startTime: "09:00", endTime: "16:00", isAvailable: true },
      { day: "Tuesday", startTime: "09:00", endTime: "16:00", isAvailable: true },
      { day: "Wednesday", startTime: "", endTime: "", isAvailable: false },
      { day: "Thursday", startTime: "09:00", endTime: "16:00", isAvailable: true },
      { day: "Friday", startTime: "09:00", endTime: "16:00", isAvailable: true },
      { day: "Saturday", startTime: "09:00", endTime: "13:00", isAvailable: true },
      { day: "Sunday", startTime: "", endTime: "", isAvailable: false },
    ],
    consultationFees: 700,
    isActive: true,
    order: 3,
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
];

export const mockServices: Service[] = [
  {
    _id: "svc_1",
    name: "Teeth Whitening",
    slug: "teeth-whitening",
    icon: "Sparkles",
    shortDescription: "Professional teeth whitening for a brighter smile",
    description:
      "Our professional teeth whitening service uses advanced laser technology to remove years of staining in just one visit. Achieve up to 8 shades whiter teeth safely and comfortably.",
    benefits: [
      "Instant results in just 60 minutes",
      "Safe and painless procedure",
      "Long-lasting results up to 2 years",
      "Professional-grade whitening agents",
      "Customized treatment for sensitivity",
    ],
    faqs: [
      {
        question: "How long does the procedure take?",
        answer: "The procedure takes approximately 60-90 minutes.",
      },
      {
        question: "Is it safe?",
        answer:
          "Yes, our whitening procedure is completely safe and supervised by experienced dentists.",
      },
      {
        question: "How long do results last?",
        answer: "Results can last up to 2 years with proper oral hygiene and maintenance.",
      },
    ],
    beforeAfterPhotos: [],
    category: "Cosmetic",
    seo: {
      metaTitle: "Professional Teeth Whitening | Urja Dental Clinic",
      metaDescription:
        "Get a brighter smile with our professional teeth whitening service. Safe, effective, and long-lasting results.",
      keywords: ["teeth whitening", "dental whitening", "smile whitening", "laser whitening"],
    },
    isActive: true,
    order: 1,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    _id: "svc_2",
    name: "Dental Implants",
    slug: "dental-implants",
    icon: "Stethoscope",
    shortDescription: "Permanent tooth replacement with dental implants",
    description:
      "Replace missing teeth permanently with our state-of-the-art dental implant solutions. We use premium titanium implants that fuse naturally with your jawbone.",
    benefits: [
      "Permanent solution for missing teeth",
      "Natural look and feel",
      "Preserves jawbone structure",
      "Improved chewing ability",
      "Lifetime durability with proper care",
    ],
    faqs: [
      {
        question: "How long do implants last?",
        answer: "With proper care, dental implants can last a lifetime.",
      },
      {
        question: "Is the procedure painful?",
        answer: "The procedure is performed under local anesthesia, ensuring minimal discomfort.",
      },
    ],
    beforeAfterPhotos: [],
    category: "Restorative",
    seo: {
      metaTitle: "Dental Implants | Urja Dental Clinic",
      metaDescription:
        "Permanent tooth replacement with premium dental implants. Natural look and feel.",
      keywords: ["dental implants", "tooth implant", "implant dentistry"],
    },
    isActive: true,
    order: 2,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    _id: "svc_3",
    name: "Root Canal Treatment",
    slug: "root-canal-treatment",
    icon: "HeartPulse",
    shortDescription: "Save your natural tooth with root canal therapy",
    description:
      "Advanced root canal treatment using rotary endodontics for faster, more comfortable procedures. Save your natural tooth and eliminate pain.",
    benefits: [
      "Saves your natural tooth",
      "Eliminates pain and infection",
      "Single-sitting RCT available",
      "Advanced rotary endodontics",
      "Minimal discomfort",
    ],
    faqs: [
      {
        question: "Does root canal hurt?",
        answer: "Modern root canal treatment is virtually painless with proper anesthesia.",
      },
    ],
    beforeAfterPhotos: [],
    category: "Restorative",
    seo: {
      metaTitle: "Root Canal Treatment | Urja Dental Clinic",
      metaDescription:
        "Painless root canal treatment using advanced technology. Save your natural tooth.",
      keywords: ["root canal", "endodontics", "RCT", "dental treatment"],
    },
    isActive: true,
    order: 3,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    _id: "svc_4",
    name: "Braces & Orthodontics",
    slug: "braces-orthodontics",
    icon: "Smile",
    shortDescription: "Straighten your teeth with modern orthodontic solutions",
    description:
      "Achieve a perfectly aligned smile with our range of orthodontic treatments including traditional braces, ceramic braces, and Invisalign clear aligners.",
    benefits: [
      "Multiple options: Metal, Ceramic, Invisalign",
      "Customized treatment plans",
      "Regular progress monitoring",
      "Suitable for all ages",
      "Affordable EMI options",
    ],
    faqs: [
      {
        question: "How long do braces take?",
        answer: "Treatment typically takes 12-24 months depending on complexity.",
      },
    ],
    beforeAfterPhotos: [],
    category: "Orthodontics",
    seo: {
      metaTitle: "Braces & Orthodontics | Urja Dental Clinic",
      metaDescription: "Straighten your teeth with braces and Invisalign. Options for all ages.",
      keywords: ["braces", "orthodontics", "invisalign", "clear aligners"],
    },
    isActive: true,
    order: 4,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    _id: "svc_5",
    name: "Dental Cleaning",
    slug: "dental-cleaning",
    icon: "Shield",
    shortDescription: "Professional dental cleaning for optimal oral health",
    description:
      "Comprehensive dental cleaning and polishing to remove plaque, tartar, and stains. Essential for maintaining optimal oral health.",
    benefits: [
      "Removes plaque and tartar",
      "Prevents gum disease",
      "Freshens breath",
      "Brighter smile",
      "Early detection of issues",
    ],
    faqs: [
      {
        question: "How often should I get cleaning?",
        answer: "We recommend professional cleaning every 6 months.",
      },
    ],
    beforeAfterPhotos: [],
    category: "Preventive",
    seo: {
      metaTitle: "Dental Cleaning | Urja Dental Clinic",
      metaDescription: "Professional dental cleaning for healthy teeth and gums.",
      keywords: ["dental cleaning", "teeth cleaning", "oral hygiene", "scaling"],
    },
    isActive: true,
    order: 5,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
];

export const mockBlogs: BlogPost[] = [
  {
    _id: "blog_1",
    title: "5 Tips for Better Oral Health",
    slug: "5-tips-for-better-oral-health",
    content: "<p>Maintaining good oral health is essential for overall well-being...</p>",
    excerpt: "Discover 5 simple tips to maintain excellent oral health and a beautiful smile.",
    featuredImage: "/blogs/oral-health-tips.jpg",
    category: "Oral Health",
    tags: ["oral health", "dental care", "tips"],
    author: "Dr. Amit Mehta",
    authorId: "doc_1",
    status: "published",
    publishDate: "2026-01-28T10:00:00Z",
    seo: {
      metaTitle: "5 Tips for Better Oral Health | Urja Dental Blog",
      metaDescription: "Learn 5 essential tips for maintaining excellent oral health.",
      keywords: ["oral health", "dental care", "dental tips"],
    },
    views: 1250,
    createdAt: "2026-01-28T10:00:00Z",
    updatedAt: "2026-01-28T10:00:00Z",
  },
  {
    _id: "blog_2",
    title: "Understanding Dental Implants: A Complete Guide",
    slug: "understanding-dental-implants-complete-guide",
    content: "<p>Dental implants are the gold standard for replacing missing teeth...</p>",
    excerpt: "Everything you need to know about dental implants - from procedure to aftercare.",
    featuredImage: "/blogs/dental-implants-guide.jpg",
    category: "Dental Procedures",
    tags: ["dental implants", "tooth replacement", "guide"],
    author: "Dr. Sneha Sharma",
    authorId: "doc_2",
    status: "published",
    publishDate: "2026-01-20T10:00:00Z",
    seo: {
      metaTitle: "Dental Implants Guide | Urja Dental Blog",
      metaDescription: "Complete guide to dental implants - procedure, benefits, and aftercare.",
      keywords: ["dental implants", "implant guide", "tooth replacement"],
    },
    views: 890,
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-01-20T10:00:00Z",
  },
  {
    _id: "blog_3",
    title: "Invisalign vs Traditional Braces: Which is Right for You?",
    slug: "invisalign-vs-traditional-braces",
    content:
      "<p>Choosing between Invisalign and traditional braces depends on several factors...</p>",
    excerpt:
      "Compare Invisalign and traditional braces to find the best orthodontic treatment for you.",
    featuredImage: "/blogs/invisalign-vs-braces.jpg",
    category: "Orthodontics",
    tags: ["invisalign", "braces", "orthodontics"],
    author: "Dr. Rajesh Gupta",
    authorId: "doc_3",
    status: "draft",
    seo: {
      metaTitle: "Invisalign vs Braces | Urja Dental Blog",
      metaDescription: "Compare Invisalign and traditional braces for orthodontic treatment.",
      keywords: ["invisalign", "braces", "orthodontics comparison"],
    },
    views: 0,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
];

export const mockGalleryImages: GalleryImage[] = [
  {
    _id: "gal_1",
    url: "/gallery/smile-1.jpg",
    thumbnail: "/gallery/smile-1-thumb.jpg",
    title: "Teeth Whitening Result",
    caption: "Amazing before and after results from professional teeth whitening",
    category: "Teeth Whitening",
    treatmentTags: ["whitening", "cosmetic"],
    order: 1,
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-01-15T10:00:00Z",
  },
  {
    _id: "gal_2",
    url: "/gallery/smile-2.jpg",
    thumbnail: "/gallery/smile-2-thumb.jpg",
    title: "Dental Implant Case",
    caption: "Complete smile restoration with dental implants",
    category: "Dental Implants",
    treatmentTags: ["implants", "restorative"],
    order: 2,
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-01-15T10:00:00Z",
  },
  {
    _id: "gal_3",
    url: "/gallery/smile-3.jpg",
    thumbnail: "/gallery/smile-3-thumb.jpg",
    title: "Smile Makeover",
    caption: "Complete smile makeover with veneers and whitening",
    category: "Smile Makeover",
    treatmentTags: ["makeover", "veneers", "cosmetic"],
    order: 3,
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-01-15T10:00:00Z",
  },
];

export const mockTestimonials: Testimonial[] = [
  {
    _id: "test_1",
    patientName: "Rahul Sharma",
    patientPhoto: "/testimonials/rahul.jpg",
    rating: 5,
    testimonial:
      "Dr. Mehta and his team are exceptional. My teeth whitening results were amazing! The clinic is modern and the staff is very friendly. Highly recommended!",
    treatment: "Teeth Whitening",
    status: "approved",
    isFeatured: true,
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-01-20T10:00:00Z",
  },
  {
    _id: "test_2",
    patientName: "Priya Patel",
    patientPhoto: "/testimonials/priya.jpg",
    rating: 5,
    testimonial:
      "I was nervous about getting dental implants, but Dr. Sneha made the entire process comfortable and painless. My new teeth look and feel natural!",
    treatment: "Dental Implants",
    status: "approved",
    isFeatured: true,
    createdAt: "2026-01-18T10:00:00Z",
    updatedAt: "2026-01-18T10:00:00Z",
  },
  {
    _id: "test_3",
    patientName: "Amit Kumar",
    rating: 4,
    testimonial:
      "Good experience with the root canal treatment. The doctor was skilled and the follow-up care was excellent.",
    treatment: "Root Canal",
    status: "pending",
    isFeatured: false,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    _id: "test_4",
    patientName: "Sneha Reddy",
    rating: 5,
    testimonial:
      "My Invisalign journey with Dr. Gupta has been fantastic. The progress tracking and regular adjustments have given me the smile I always wanted.",
    treatment: "Invisalign",
    status: "approved",
    isFeatured: false,
    createdAt: "2026-01-25T10:00:00Z",
    updatedAt: "2026-01-25T10:00:00Z",
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    _id: "enq_1",
    name: "Kavita Nair",
    phone: "+91 98765 11111",
    email: "kavita.nair@email.com",
    subject: "Dental Implant Pricing",
    message:
      "I would like to know the cost of dental implants for 2 missing teeth. Do you offer EMI options?",
    status: "new",
    internalNotes: [],
    conversationHistory: [],
    createdAt: "2026-02-05T14:00:00Z",
    updatedAt: "2026-02-05T14:00:00Z",
  },
  {
    _id: "enq_2",
    name: "Rohit Verma",
    phone: "+91 98765 22222",
    email: "rohit.v@email.com",
    subject: "Braces Consultation",
    message: "I'm interested in getting Invisalign. Can you tell me about the duration and cost?",
    status: "in_progress",
    assignedTo: "Dr. Rajesh Gupta",
    internalNotes: [
      {
        _id: "note_1",
        content: "Patient has mild crowding, good candidate for Invisalign",
        createdBy: "Front Desk",
        createdAt: "2026-02-04T10:00:00Z",
      },
    ],
    conversationHistory: [
      {
        _id: "msg_1",
        type: "email",
        content:
          "Thank you for your enquiry. We have shared the Invisalign brochure and pricing details.",
        sentBy: "Front Desk",
        sentAt: "2026-02-04T11:00:00Z",
      },
    ],
    createdAt: "2026-02-03T09:00:00Z",
    updatedAt: "2026-02-04T11:00:00Z",
  },
  {
    _id: "enq_3",
    name: "Meera Joshi",
    phone: "+91 98765 33333",
    email: "meera.j@email.com",
    subject: "Appointment Rescheduling",
    message: "I need to reschedule my appointment from Feb 8 to Feb 12. Is that possible?",
    status: "closed",
    internalNotes: [],
    conversationHistory: [
      {
        _id: "msg_2",
        type: "email",
        content: "Your appointment has been rescheduled to Feb 12 at 3:00 PM.",
        sentBy: "Front Desk",
        sentAt: "2026-02-05T10:00:00Z",
      },
    ],
    createdAt: "2026-02-05T08:00:00Z",
    updatedAt: "2026-02-05T10:00:00Z",
  },
];

export const mockUsers: User[] = [
  {
    _id: "usr_1",
    name: "Admin Owner",
    email: "admin@urjadental.com",
    role: "owner",
    isActive: true,
    lastLogin: "2026-02-06T09:00:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-02-06T09:00:00Z",
  },
  {
    _id: "usr_2",
    name: "Dr. Amit Mehta",
    email: "amit.mehta@urjadental.com",
    role: "doctor",
    isActive: true,
    lastLogin: "2026-02-06T08:30:00Z",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-02-06T08:30:00Z",
  },
  {
    _id: "usr_3",
    name: "Reception Staff",
    email: "reception@urjadental.com",
    role: "front_desk",
    isActive: true,
    lastLogin: "2026-02-06T09:15:00Z",
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2026-02-06T09:15:00Z",
  },
  {
    _id: "usr_4",
    name: "Content Editor",
    email: "editor@urjadental.com",
    role: "editor",
    isActive: true,
    lastLogin: "2026-02-05T14:00:00Z",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-02-05T14:00:00Z",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    _id: "log_1",
    user: "Admin Owner",
    userId: "usr_1",
    action: "Login",
    module: "Authentication",
    details: "Successful login from Chrome on macOS",
    ipAddress: "192.168.1.100",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    createdAt: "2026-02-06T09:00:00Z",
  },
  {
    _id: "log_2",
    user: "Reception Staff",
    userId: "usr_3",
    action: "Created",
    module: "Appointments",
    details: "New appointment created for Rahul Sharma",
    ipAddress: "192.168.1.101",
    createdAt: "2026-02-06T09:15:00Z",
  },
  {
    _id: "log_3",
    user: "Content Editor",
    userId: "usr_4",
    action: "Published",
    module: "Blogs",
    details: 'Blog post "5 Tips for Better Oral Health" published',
    ipAddress: "192.168.1.102",
    createdAt: "2026-02-05T14:00:00Z",
  },
  {
    _id: "log_4",
    user: "Admin Owner",
    userId: "usr_1",
    action: "Updated",
    module: "Settings",
    details: "Clinic timings updated for Saturday",
    ipAddress: "192.168.1.100",
    createdAt: "2026-02-05T11:00:00Z",
  },
  {
    _id: "log_5",
    user: "Dr. Amit Mehta",
    userId: "usr_2",
    action: "Updated",
    module: "Patients",
    details: "Medical notes added for patient Amit Kumar",
    ipAddress: "192.168.1.103",
    createdAt: "2026-02-05T10:30:00Z",
  },
];

export const mockBackups: Backup[] = [
  {
    _id: "bak_1",
    type: "automatic",
    status: "completed",
    databaseSize: "45.2 MB",
    mediaSize: "2.3 GB",
    createdAt: "2026-02-06T02:00:00Z",
    completedAt: "2026-02-06T02:15:00Z",
  },
  {
    _id: "bak_2",
    type: "automatic",
    status: "completed",
    databaseSize: "44.8 MB",
    mediaSize: "2.2 GB",
    createdAt: "2026-02-05T02:00:00Z",
    completedAt: "2026-02-05T02:12:00Z",
  },
  {
    _id: "bak_3",
    type: "manual",
    status: "completed",
    databaseSize: "44.5 MB",
    mediaSize: "2.1 GB",
    createdAt: "2026-02-04T15:00:00Z",
    completedAt: "2026-02-04T15:18:00Z",
  },
  {
    _id: "bak_4",
    type: "automatic",
    status: "completed",
    databaseSize: "44.1 MB",
    mediaSize: "2.1 GB",
    createdAt: "2026-02-04T02:00:00Z",
    completedAt: "2026-02-04T02:14:00Z",
  },
];

export const mockRedirects: Redirect[] = [
  {
    _id: "red_1",
    oldUrl: "/old-services-page",
    newUrl: "/services",
    type: 301,
    isActive: true,
    hits: 45,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-02-01T00:00:00Z",
  },
  {
    _id: "red_2",
    oldUrl: "/about-us",
    newUrl: "/about",
    type: 301,
    isActive: true,
    hits: 128,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
  {
    _id: "red_3",
    oldUrl: "/promo/new-year",
    newUrl: "/offers",
    type: 302,
    isActive: false,
    hits: 67,
    createdAt: "2025-12-28T00:00:00Z",
    updatedAt: "2026-01-05T00:00:00Z",
  },
];

export const mockSEOScores: SEOScore[] = [
  {
    page: "Home",
    score: 92,
    checks: [
      { type: "success", message: "Meta title length is optimal (55 characters)" },
      { type: "success", message: "Meta description length is optimal (150 characters)" },
      { type: "success", message: "H1 tag present" },
      { type: "warning", message: "3 images missing alt tags" },
      { type: "success", message: "Keywords properly used in content" },
    ],
  },
  {
    page: "About",
    score: 85,
    checks: [
      { type: "success", message: "Meta title length is optimal" },
      { type: "warning", message: "Meta description could be longer" },
      { type: "success", message: "H1 tag present" },
      { type: "success", message: "All images have alt tags" },
    ],
  },
  {
    page: "Services",
    score: 78,
    checks: [
      { type: "success", message: "Meta title length is optimal" },
      { type: "success", message: "Meta description length is optimal" },
      { type: "error", message: "Multiple H1 tags found" },
      { type: "warning", message: "5 images missing alt tags" },
    ],
  },
  {
    page: "Blog",
    score: 88,
    checks: [
      { type: "success", message: "Meta title length is optimal" },
      { type: "success", message: "Meta description length is optimal" },
      { type: "success", message: "Proper heading structure" },
      { type: "warning", message: "2 images missing alt tags" },
    ],
  },
];
